spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: lxy17305692312.
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
#    publisher-confirms: true
    publisher-returns: true
    port: 5672
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
  cache:
    cache-names:
      - menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/
authing:
  config:
    appId: 637ecbd24f933bcfd0b0a31e
    appSecret: 273360dddea3702eae1bbb7b42dd21d0
    appHost: https://kuluqi5.authing.cn
    userPoolId: 637ecbd1ed27599255387fa1
    userPoolSecret: e52bdf290082ada8854af4924fd56e32
    redirectUri: http://127.0.0.1:8081/callback